Shop\Domain\Model\Product:
    properties:
        id:
            - NotBlank: ~
        name:
            - NotBlank: ~
            - Length:
                max: 255
        description:
            - Length:
                min: 100
                max: 65000
        addedAt:
            - DateTime: ~