# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Shop\Domain\Model\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    providers:
#        user_db:
#            entity:
#                class: Shop\Domain\Model\User
#                property: email
        my_mongo_provider:
            mongodb:
                class: Shop\Domain\Model\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            form_login:
                login_path: admin_login
                check_path: admin_login
                always_use_default_target_path: false
                default_target_path:            admin_homepage
                target_path_parameter:          _target_path
                use_referer:                    false

            logout:
                path:   admin_logout
                target: admin_login
                invalidate_session: false

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_USER }
