parameters:
    #parameter_name: value
    container.autowiring.strict_mode: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
    AppBundle\Menu\MenuBuilder:
        arguments: ['@knp_menu.factory', '@security.authorization_checker', '@request_stack']
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
    AppBundle\Twig\MoneyFormatExtension:
        public: false
        tags:
            - { name: twig.extension }
    # pass currencies to PriceType form
    AppBundle\Form\PriceType:
        arguments: [['PLN', 'EUR', 'USD']]
        tags:
            - { name: form.type }
    Shop\Domain\Command\NewProductHandler:
        arguments: ['@Shop\Infrastructure\Repository\Doctrine\ProductRepository', '@validator', '@Shop\Infrastructure\Transport\Mailer']
    Shop\Infrastructure\Repository\Doctrine\ProductRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Shop\Domain\Model\Product
    Shop\Infrastructure\Transport\Mailer:
        arguments: ['@swiftmailer.mailer', '@twig']
