Shop\Domain\Model\Product:
    db: washop
    collection: product
    repositoryClass: Shop\Infrastructure\Repository\Doctrine\ProductRepository
    fields:
        id:
            type: id
            id:  true
            strategy: NONE
        name:
            type: string
        description:
            type: string
        priceAmount:
            type: float
        priceCurrency:
            type: string
        addedAt:
            type: date
        user:
            reference: true
            type: one
            targetDocument: Shop\Domain\Model\User
            cascade: all
